# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mc_question_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mc_question(object):
    def setupUi(self, mc_question):
        mc_question.setObjectName("mc_question")
        mc_question.resize(963, 720)
        self.title = QtWidgets.QLabel(mc_question)
        self.title.setGeometry(QtCore.QRect(160, 10, 441, 16))
        self.title.setObjectName("title")
        self.context = QtWidgets.QLabel(mc_question)
        self.context.setGeometry(QtCore.QRect(160, 40, 511, 16))
        self.context.setObjectName("context")
        self.frame_top = QtWidgets.QFrame(mc_question)
        self.frame_top.setGeometry(QtCore.QRect(30, 70, 761, 441))
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.question = QtWidgets.QLabel(self.frame_top)
        self.question.setGeometry(QtCore.QRect(30, 10, 161, 16))
        self.question.setObjectName("question")
        self.frame_question = QtWidgets.QFrame(self.frame_top)
        self.frame_question.setGeometry(QtCore.QRect(60, 30, 671, 261))
        self.frame_question.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_question.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_question.setObjectName("frame_question")
        self.frame_3 = QtWidgets.QFrame(self.frame_question)
        self.frame_3.setGeometry(QtCore.QRect(30, 20, 611, 41))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.button_answer_1 = QtWidgets.QPushButton(self.frame_3)
        self.button_answer_1.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.button_answer_1.setObjectName("button_answer_1")
        self.answer_1 = QtWidgets.QLabel(self.frame_3)
        self.answer_1.setGeometry(QtCore.QRect(120, 10, 501, 16))
        self.answer_1.setObjectName("answer_1")
        self.frame_4 = QtWidgets.QFrame(self.frame_question)
        self.frame_4.setGeometry(QtCore.QRect(30, 80, 611, 41))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.button_answer_2 = QtWidgets.QPushButton(self.frame_4)
        self.button_answer_2.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.button_answer_2.setObjectName("button_answer_2")
        self.answer_2 = QtWidgets.QLabel(self.frame_4)
        self.answer_2.setGeometry(QtCore.QRect(120, 10, 471, 16))
        self.answer_2.setObjectName("answer_2")
        self.answer_3 = QtWidgets.QFrame(self.frame_question)
        self.answer_3.setGeometry(QtCore.QRect(30, 140, 611, 41))
        self.answer_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.answer_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.answer_3.setObjectName("answer_3")
        self.button_answer_3 = QtWidgets.QPushButton(self.answer_3)
        self.button_answer_3.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.button_answer_3.setObjectName("button_answer_3")
        self.answer_5 = QtWidgets.QLabel(self.answer_3)
        self.answer_5.setGeometry(QtCore.QRect(120, 10, 471, 16))
        self.answer_5.setObjectName("answer_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_question)
        self.frame_6.setGeometry(QtCore.QRect(30, 200, 611, 41))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.button_answer_4 = QtWidgets.QPushButton(self.frame_6)
        self.button_answer_4.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.button_answer_4.setObjectName("button_answer_4")
        self.answer_4 = QtWidgets.QLabel(self.frame_6)
        self.answer_4.setGeometry(QtCore.QRect(120, 10, 501, 16))
        self.answer_4.setObjectName("answer_4")
        self.feedback = QtWidgets.QLabel(self.frame_top)
        self.feedback.setGeometry(QtCore.QRect(60, 310, 671, 41))
        self.feedback.setObjectName("feedback")
        self.button_next = QtWidgets.QPushButton(self.frame_top)
        self.button_next.setGeometry(QtCore.QRect(40, 360, 611, 28))
        self.button_next.setObjectName("button_next")

        self.retranslateUi(mc_question)
        QtCore.QMetaObject.connectSlotsByName(mc_question)

    def retranslateUi(self, mc_question):
        _translate = QtCore.QCoreApplication.translate
        mc_question.setWindowTitle(_translate("mc_question", "Form"))
        self.title.setText(_translate("mc_question", "title"))
        self.context.setText(_translate("mc_question", "context"))
        self.question.setText(_translate("mc_question", "question"))
        self.button_answer_1.setText(_translate("mc_question", "A"))
        self.answer_1.setText(_translate("mc_question", "answer_1"))
        self.button_answer_2.setText(_translate("mc_question", "B"))
        self.answer_2.setText(_translate("mc_question", "answer_2"))
        self.button_answer_3.setText(_translate("mc_question", "C"))
        self.answer_5.setText(_translate("mc_question", "answer_3"))
        self.button_answer_4.setText(_translate("mc_question", "D"))
        self.answer_4.setText(_translate("mc_question", "answer_4"))
        self.feedback.setText(_translate("mc_question", "feedback"))
        self.button_next.setText(_translate("mc_question", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mc_question = QtWidgets.QWidget()
    ui = Ui_mc_question()
    ui.setupUi(mc_question)
    mc_question.show()
    sys.exit(app.exec_())
